name: Continuous Integration

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build Tori
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Build code
        run: npm run clean-build
  lint:
    name: Lint Tori
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true
      - name: Install Node.js v18
        uses: actions/setup-node@v3
        with:
          cache: 'npm'
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Lint code
        run: npm run lint